name: Auto Merge Post-List Create JSON 

on:
  # src/data 폴더 내 파일 변경 감지 시 자동 실행  
  # push:
  #  paths:
  #    - 'src/data/**'      # src/data 폴더 및 하위 모든 파일 읽기
  #  branches:
  #    - main               # 브랜치명 확인
  schedule:                 # 매 시간마다 실행 (UTC 기준)
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:        # 수동 트리거 허용

concurrency:                # 동시 실행 방지 설정
  group: "merge-data"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run Merge Script
        run: node merge-batch.js

      - name: Commit and Push changes
        run: |
          # 1. 로봇 계정 설정
          git config --global user.name "merge_bot"
          git config --global user.email "merge_bot@users.noreply.github.com"
          
          # 2. 배치 스크립트이 생성한 결과물 파일만 추가
          git add src/data/total_posts.json src/data/recent_3.json
          
          # 3. 변경 사항이 있을 때만 커밋하고 푸시 (무한 루프 방지 [skip ci] 포함)
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: auto-update merged data [skip ci]" && git push)
